// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tenxnfduxdgybnocikkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlbnhuZmR1eGRneWJub2Npa2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwOTEwNjgsImV4cCI6MjA4NDY2NzA2OH0.jI07BzJwYiOsucNkGSOzZOvxhw2piuRc4D93O_fl9mY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});